### ISSUE TITLE
Generalized field property

### ISSUE THREAD

**Issue by felixwellen** [eqNat/Math#1]
Hi - I just want to make you aware of the generalized field property in case you don't know it. You can view it here, where it is proven from something else, but I think it would be a reasonable additional axiom for a 'field':

https://github.com/felixwellen/synthetic-geometry/blob/main/SyntheticGeometry/SQC/Consequences.lagda.md

It is a consequence of the constructive notion of 'local ring' together with the axiom you use for 'field', i.e. that non-zero elements are invertible. One way to use the generalized field property is to conclude that any non-zero sum has an invertible summand. It also helps with showing that non-zero matrices have an echelon form.

**Comment by jhimes2** [comment]
Thank you for the recommendation. I was not aware of the generalized field property before.

 I would rather prove the property rather than requiring it as an axiom so my 'Field' definition can be as inclusive as possible, or just so I don't have to prove it for every instance.  Is the following statement sufficient?

`{{F : Field A}} → (xs : [ A ^ n ]) → xs ≢ (λ _ → zero) → ¬ ¬ (Σ λ(i : fin n) → (xs i ∈ A ˣ))`

I can eliminate the double negation with the premise `(x : A) → Dec (x ≡ zero)`, but that might be too strong of a requirement since I just need to replace double negation with propositional truncation to match your conclusion.

Or would you suggest defining it the way you did it?

````agda
{{CR : CRing A}}
  → isLocal A
  → sqc-over-itself A
  → (xs : [ A ^ n ]) → xs ≢ (λ _ → zero) → ∃ λ(i : fin n) → (xs i ∈ A ˣ)

**Comment by felixwellen** [comment]
I don't see how your statement can be sufficient in general and you shouldn't be able to prove the generalized field property for an arbitrary field ('field' in the sense that non-zero elements are invertible and zero is different from one). It is an additional axiom which makes a lot of things possible. A milder version is to ask that any non-zero vector (i.e. finite list of elements of the field) which is different from the zero vector has a non-zero entry.
The property ```(x : A) → Dec (x ≡ zero)``` implies the generalized field property, but not the other way around. 
Hope that helps!

**Comment by felixwellen** [comment]
> Or would you suggest defining it the way you did it?

Definitely not ;-) We prove things for a ring which has the sqc property, which is an *extremely strong* requirement - you have to go outside the (classical) topos of sets to have any chance to find an example...

**Comment by felixwellen** [comment]
Oh sorry, if you just mean the statement in the last line you quoted, then yes, this would be a way to define the generalized field property.
But as mentioned above, you could also say field in the above sense and ask for the additional property that non-zero vectors (merely) have non-zero entries - which I think is a very natural thing to ask for.

**Comment by jhimes2** [comment]
Included the generalized field property as an axiom.
